name: Setup Plugin

on:
  create:

jobs:
  setup:
    if: github.run_number == 1
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Initialize
        run: |
          rm -rf LICENSE
          rm -rf README.*
          rm -rf .github/workflows/setup.yml
          echo "# ${{ github.event.repository.name }}" > README.md
          sed -i "s/%author%/${{ github.repository_owner }}/g" ./plugin/Plugin.php
          sed -i "s|%link%|${{ github.event.repository.html_url }}|g" ./plugin/Plugin.php
          sed -i "s/%name%/${{ github.event.repository.name }}/g" ./plugin/Plugin.php
          sed -i "s/%description%/${{ github.event.description }}/g" ./plugin/Plugin.php

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Setup project for ${{ github.event.repository.name }}"