name: Setup Plugin

on:
  create:

jobs:
  setup:
    if: github.run_number == 1
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Initialize
        run: |
          rm -rf LICENSE
          rm -rf README.*
          echo "# ${{ github.event.repository.name }}" > README.md

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Setup project for ${{ github.event.repository.name }}"